Add flag that allows user to set the timestamp format
ceuk/rofi-screenshot pull request #4
Opened 2023-02-06 20:09 UTC by seanhagen

The default date format "`+%d-%m-%Y %H:%M:%S`" doesn't work for me; it causes issues with files that [syncthing](https://syncthing.net/) trying to sync screenshots to devices that can't handle files with special characters in the filename.

So I added a 'default' date format, and a flag that allows the user to override what the date format is if they want.

Also pulled the evalling of `date` out of each function and passing in the computed timestamp string into the functions that need it to make it clear they all share the same timestamp format. I also felt it was a bit cleaner than passing the _format_ into each function and each function calling `date` to compute the timestamp string.

2023-02-14 20:17 UTC, ceuk requested changes

2023-02-14 20:17 UTC, ceuk commented on rofi-screenshot
> +  date_format="$default_date_format"
So the original method of checking the args was pretty rubbish in this, but I figured it was fine since no-one would ever need to use both `-s` and `-d` at the same time. 

However, now we have an issue in that it's conceivable that people will want to use both `-t` and `-d` in which case the second arg would just be ignored currently. 

Would you mind fixing the arg parsing so that it would support multiple args? 

Apart from that the rest of this LGTM - thanks for the nice addition :)

2023-02-14 21:38 UTC, seanhagen commented on rofi-screenshot
> +  date_format="$default_date_format"
Done! Tested, and multiple args at once works 😄

2023-02-17 10:45 UTC, ceuk commented on rofi-screenshot
> +  date_format="$default_date_format"
Perfect - cheers!

2023-02-17 10:45 UTC, merged